/// Represents the response to a user query, including the generated search query,
/// the original user question, the final answer, and all retrieved contexts.
class QueryResponse {
  /// The original question asked by the user.
  final String userQuestion;

  /// The search query generated by the system to fetch relevant contexts.
  final String generatedSearchQuery;

  /// A list of [RetrievedContext] objects containing metadata and snippets from documents.
  final List<RetrievedContext> retrievedContext;

  /// The final answer generated based on the retrieved contexts.
  final String finalAnswer;

  /// Constructs a [QueryResponse] with all necessary components.
  QueryResponse({
    required this.userQuestion,
    required this.generatedSearchQuery,
    required this.retrievedContext,
    required this.finalAnswer,
  });

  /// Creates a [QueryResponse] instance from a JSON map.
  ///
  /// Expects keys:
  /// - "user_question": String
  /// - "generated_search_query": String
  /// - "retrieved_context": List of JSON objects for [RetrievedContext]
  /// - "final_answer": String
  factory QueryResponse.fromJson(Map<String, dynamic> json) {
    return QueryResponse(
      userQuestion: json['user_question'] as String,
      generatedSearchQuery: json['generated_search_query'] as String,
      retrievedContext: (json['retrieved_context'] as List)
          .map((item) => RetrievedContext.fromJson(item as Map<String, dynamic>))
          .toList(),
      finalAnswer: json['final_answer'] as String,
    );
  }
}

/// Represents a snippet of context retrieved from a document in response to a query.
///
/// Contains metadata about the context's relevance and a short snippet of the document text.
class RetrievedContext {
  /// Unique identifier of the document where the context was found.
  final String docId;

  /// Semantic similarity score between the user query and this context (range 0.0 - 1.0).
  final double semanticSimilarity;

  /// Ratio of matching n-grams between the query and the context (as a percentage).
  final int ngramMatchRatio;

  /// A short snippet of text from the document that matches the query.
  final String textSnippet;

  /// Constructs a [RetrievedContext] with the given metadata and text snippet.
  RetrievedContext({
    required this.docId,
    required this.semanticSimilarity,
    required this.ngramMatchRatio,
    required this.textSnippet,
  });

  /// Creates a [RetrievedContext] instance from a JSON map.
  ///
  /// Expects keys:
  /// - "doc_id": String
  /// - "semantic_similarity": num or String convertible to double
  /// - "ngram_match_ratio": int
  /// - "text_snippet": String
  factory RetrievedContext.fromJson(Map<String, dynamic> json) {
    return RetrievedContext(
      docId: json['doc_id'] as String,
      semanticSimilarity: (json['semantic_similarity'] as num).toDouble(),
      ngramMatchRatio: json['ngram_match_ratio'] as int,
      textSnippet: json['text_snippet'] as String,
    );
  }
}